name: Deploy JSDoc and Doxygen to GitHub Pages

on:
  push:
    branches: [ main ] # Or your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Install and Generate Doxygen and JSDoc
        run: |
          npm install -g jsdoc
          sudo apt-get update
          sudo apt-get install -y doxygen

      - name: Generate Frontend Docs
        run: npx jsdoc -r Madonna/ -d ./docs/frontend

      - name: Generate Backend Docs
        run: doxygen Doxyfile

      - name: add .nojekyll file
        run: touch ./docs/.nojekyll

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs # The folder the action should deploy
          branch: gh-pages # The branch the action deploys to